### ISSUE TITLE
zguide/examples/C build script failure

### ISSUE THREAD

**Issue by wluker** [booksbyus/zguide#396]
In zguide/examples/C there is a bug either in the /bin/sh script ./build or ./c 
Under Linux, the wrong command is passed to gcc.
For example:
./build hwserver 
produces:
gcc  -I/usr/local/include -L/usr/local/lib **-lczmq -lzmq**  -O2 -D_REENTRANT -D_GNU_SOURCE -Wall -Wno-unused -fno-strict-aliasing  -DBASE_THREADSAFE hwserver.o -o hwserver -Wl,--start-group  -lpthread -lm -lrt -lcrypt -luuid  -Wl,--end-group -L. -L. -L. -lpthread -lm -lrt -lcrypt -luuid

which fails with linker errors:
undefined reference to zmq_ctx_new
...
undefined reference to zmq_send

The build script should produce something like this:
gcc  -I/usr/local/include -L/usr/local/lib  -O2 -D_REENTRANT -D_GNU_SOURCE -Wall -Wno-unused -fno-strict-aliasing  -DBASE_THREADSAFE hwserver.o -o hwserver -Wl,--start-group  -lpthread -lm -lrt -lcrypt -luuid  -Wl,--end-group -L. -L. -L. -lpthread -lm -lrt -lcrypt -luuid **-lczmq -lzmq**

Which then links as desired.

**Comment by TafThorne** [comment]
I am trying to get the C examples to compile on Ubuntu 16.04 and having no luck at all.  Initially my problem looked like the one described in this issue but now I am not sure if the default Ubuntu packages or the ones provided from the main zmq site work with 16.04 at all.  I have messed about so much I am not sure where I am.  I can now get to the point of seeing:
```
$ ./build hwserver
hwserver
/usr/bin/ld: cannot find -lczmq
collect2: error: ld returned 1 exit status
```
Which was only after I manually installed the _uuid_ package.

**Comment by TafThorne** [comment]
Well I figured out my biggest problem.  It was that `libzmq-dev`, `libzmq3-dev` and `libczmq3` are all seperate packages that need installing.  Once I had that straight everything was alright again without any changes to the `build` script.
